stages:
  - build

build:
  stage: build
  image: dhub.rnd.lanit.ru/docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $CI_REGISTRY/${CI_PROJECT_NAME}:latest .
    - docker push $CI_REGISTRY/${CI_PROJECT_NAME}:latest
